{% set name = "chemcat" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/chemcat-{{ version }}.tar.gz
  sha256: 17f7cc0712da94eab2dc42a71def78d730e2595629de33896e50b8b777fe62fb

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [win]
requirements:
  build:
    - {{ compiler('c') }}
  host:
    - numpy
    - pip
    - python
  run:
    - matplotlib-base >=3.3.4
    - more-itertools >=8.4.0
    - numpy >=1.19.1
    - python
    - scipy >=1.5.2
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - chemcat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/atmolib/chemcat
  summary: Chemistry Calculator for Atmospheres
  license: GPL-2.0
  license_file:
    - LICENSE
  dev_url: https://github.com/atmolib/chemcat
  doc_url: https://chemcat.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pcubillos
