{% set name = "chemcat" %}
{% set version = "0.3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/chemcat-{{ version }}.tar.gz
  sha256: 64296880763d5531bcb9a8d9e2bbad3e5637b009892ed79a60064b9059a0f9b8

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [win]
requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - numpy
    - pip
    - python
  run:
    - matplotlib-base >=3.3.4
    - more-itertools >=8.4.0
    - numpy >=1.19.1
    - python
    - scipy >=1.5.2

test:
  imports:
    - chemcat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/atmolib/chemcat
  summary: Chemistry Calculator for Atmospheres
  license: GPL-2.0
  license_file:
    - LICENSE
  dev_url: https://github.com/atmolib/chemcat
  doc_url: https://chemcat.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pcubillos
