{% set name = "chemcat" %}
{% set version = "0.3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/chemcat-{{ version }}.tar.gz
  sha256: 4a0e951d5506055056ee67cb0d93de6a4f8c51b20393154c602c5b91900b795b

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  skip: true  # [win]
  skip: true  # [py<39]
requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - numpy
  run:
    - python
    - matplotlib-base >=3.9.2
    - more-itertools >=8.4.0
    - numpy >=2.0.0
    - scipy >=1.13.0

test:
  imports:
    - chemcat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/atmolib/chemcat
  summary: Chemistry Calculator for Atmospheres
  license: GPL-2.0-or-later
  license_file:
    - LICENSE
  dev_url: https://github.com/atmolib/chemcat
  doc_url: https://chemcat.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pcubillos
